/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week2;

import java.util.Random;

/**
 *
 * @author Guest-Student
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genint = new javax.swing.JButton();
        text1 = new javax.swing.JLabel();
        gendouble = new javax.swing.JButton();
        text2 = new javax.swing.JLabel();
        genstring = new javax.swing.JButton();
        text3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("test_random");

        genint.setBackground(new java.awt.Color(255, 204, 255));
        genint.setText("gen int");
        genint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genintActionPerformed(evt);
            }
        });

        text1.setText("Gen 10 random ints");

        gendouble.setText("gen double");
        gendouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendoubleActionPerformed(evt);
            }
        });

        text2.setText("Gen 10 random double");

        genstring.setText("gen string");
        genstring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genstringActionPerformed(evt);
            }
        });

        text3.setText("Gen 10 random strings");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text1)
                    .addComponent(text2)
                    .addComponent(text3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(genstring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gendouble, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genint)
                    .addComponent(text1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gendouble)
                    .addComponent(text2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genstring)
                    .addComponent(text3))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //genint button
    private void genintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genintActionPerformed
        Random random = new Random();

        StringBuilder str = new StringBuilder();
        for (int i = 0; i < 10; i++) {
            int x = random.nextInt(101);
//            System.out.println(x);

            str.append(x);

            if (i < 9) {
                str.append(", ");
            }
        }
        text1.setText(str.toString());

    }//GEN-LAST:event_genintActionPerformed

    private void gendoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gendoubleActionPerformed
        // TODO add your handling code here:
        Random random = new Random();
        String str = new String();
          for (int i = 0; i < 10; i++) {
            double x = random.nextInt(21)+10;
            double y = (random.nextInt(9)+1)/10.;
            double result = x + y;
            str += result;
            if(i<9){
                str += ", ";
            }
        }
        text2.setText(str);
    }//GEN-LAST:event_gendoubleActionPerformed

    private void genstringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genstringActionPerformed
        // TODO add your handling code here:
        Random random = new Random();
        String result = new String();
        String str1 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        for(int i=0;i<10;i++){
            char x = str1.charAt(random.nextInt(26));

            result += x;
            if(i<9){
                result += ", ";
            }
        }
        text3.setText(result);
        
    }//GEN-LAST:event_genstringActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gendouble;
    private javax.swing.JButton genint;
    private javax.swing.JButton genstring;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    // End of variables declaration//GEN-END:variables
}
